[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ICS"
version = "3.0.0"
description = ""
readme = "README.rst"
classifiers = [
    "Programming Language :: Python :: 3"
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
icsd = "ics.icsd:main"
icsstart = "ics.command_line:icsstart"
icsstop = "ics.command_line:icsstop"
icssys = "ics.command_line:icssys"
icsgrp = "ics.command_line:icsgrp"
icsres = "ics.command_line:icsres"
icsalert = "ics.command_line:icsalert"
icsdump = "ics.command_line:icsdump"
